export const CREATE_TODO = "todo/createTodo"
export const TOGGLE_TODO = "todo/toggleTodo"
export const REMOVE_TODO = "todo/deleteTodo"
export const INIT_TODO = "todo/initTodo"
export const UPDATE_TODO = "todo/updateTodo"
